[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "py_carlo"
version = "0.0.1"
description = "Simple Monte-Carlo Simulations"
dependencies = [
    "pandas",
    "tqdm",
    'importlib-metadata; python_version>="3.10"'

]